### ISSUE TITLE
Support Category Exclusions

### ISSUE THREAD

**Issue by pigmonkey** [ProLoser/funcheapmap#11]
My biggest difficulty in using the Funcheap website is the constant flood of comedy shows that I don't care about.

On your map, I would prefer the ability to select categories to exclude rather than categories to filter by. Maybe there could just be an "exclude" checkbox below the category list that flips the behaviour?

It would also be nice if the category list supported multi-select.

**Comment by ProLoser** [comment]
@pigmonkey done

**Comment by ProLoser** [comment]
Actually in retrospect, I only implemented half of your suggestion:

The category drop down now lets you select multiple categories. At first I was thinking this enables you to select everything _except_ standup, but the way I coded it you will still see some standup results if they have multiple categories.

Adding a negative or exclusion rule greatly increases the complexity of the website, there isn't really an off-the-self solution for what you're describing, it's usually a search input that recognizes special patterns like `-donotincludeme` but I would have to create a completely new control input just to negate or exclude search results.

In the end, that seems like a very trivial inconvenience. Please let me know if the multiselect is useful. If it doesn't really help I may revert it because it looks kinda weird on desktop

**Comment by pigmonkey** [comment]
The multiselect is helpful, thanks. Since the category selections end up as querystrings, I can figure out what combination of categories I want and then just bookmark that URL.

Maybe throwing Select2 or something similar at that element would make it look less clunky.
